spring:
  application:
    name: simbiosys-consumer
  docker:
    compose:
      enabled: false

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: projetosimbiosys@gmail.com
    password: smxbmfhprfwfxsoz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
        debug: true

app:
  queue:
    name: relatorioQueue
  destinatario:
    email: matheusferrotorres@gmail.com

server:
  port: 8082
